// <auto-generated />
using System;
using OpenTrpg.Core.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace OpenTrpg.Core.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005174015_AddCatalog")]
    partial class AddCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenTrpg.Core.Domain.Campaigns.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Campaigns", (string)null);
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Campaigns.CampaignMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CampaignId", "UserId")
                        .IsUnique();

                    b.ToTable("CampaignMembers", (string)null);
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Campaigns.OwnershipTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreviousOwnerNewRole")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("TransferredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("OwnershipTransfers", (string)null);
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Catalog.BackgroundDefinition", b =>
                {
                    b.Property<string>("Index")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FeatureDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SkillProficiencies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StartingEquipmentText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Index");

                    b.HasIndex("Name");

                    b.ToTable("CatalogBackgrounds", (string)null);
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Catalog.CatalogImport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CountsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DatasetVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ruleset")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Ruleset", "DatasetVersion")
                        .IsUnique();

                    b.ToTable("CatalogImports", (string)null);
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Catalog.ClassDefinition", b =>
                {
                    b.Property<string>("Index")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("HitDie")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPactCaster")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSpellcaster")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProficiencyNames")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SavingThrows")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpellcastingAbility")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("SpellcastingLevel")
                        .HasColumnType("integer");

                    b.Property<string>("StartingEquipmentText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubclassFlavor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Index");

                    b.HasIndex("Name");

                    b.ToTable("CatalogClasses", (string)null);
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Catalog.ClassLevel", b =>
                {
                    b.Property<string>("Index")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("AbilityScoreBonuses")
                        .HasColumnType("integer");

                    b.Property<int?>("CantripsKnown")
                        .HasColumnType("integer");

                    b.Property<string>("ClassIndex")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClassSpecificJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeatureIndexes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("ProfBonus")
                        .HasColumnType("integer");

                    b.Property<string>("SpellSlots")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SpellsKnown")
                        .HasColumnType("integer");

                    b.HasKey("Index");

                    b.HasIndex("ClassIndex", "Level")
                        .IsUnique();

                    b.ToTable("CatalogClassLevels", (string)null);
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Catalog.ConditionDefinition", b =>
                {
                    b.Property<string>("Index")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Index");

                    b.HasIndex("Name");

                    b.ToTable("CatalogConditions", (string)null);
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Catalog.FeatureDefinition", b =>
                {
                    b.Property<string>("Index")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClassIndex")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SubclassIndex")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Index");

                    b.HasIndex("Name");

                    b.HasIndex("SubclassIndex");

                    b.HasIndex("ClassIndex", "Level");

                    b.ToTable("CatalogFeatures", (string)null);
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Catalog.ItemTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool?>("AddDexModifier")
                        .HasColumnType("boolean");

                    b.Property<int?>("ArmorClassBase")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("CostCp")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DamageDice")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DamageType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Index")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("MaxDexBonus")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RangeLong")
                        .HasColumnType("integer");

                    b.Property<int?>("RangeNormal")
                        .HasColumnType("integer");

                    b.Property<string>("Rarity")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("RequiresAttunement")
                        .HasColumnType("boolean");

                    b.Property<bool>("StealthDisadvantage")
                        .HasColumnType("boolean");

                    b.Property<int?>("StrengthMinimum")
                        .HasColumnType("integer");

                    b.Property<string>("Subcategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VersatileDice")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("WeightLb")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Index")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("CampaignId", "Name");

                    b.ToTable("ItemTemplates", (string)null);
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Catalog.RaceDefinition", b =>
                {
                    b.Property<string>("Index")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AbilityBonusesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Alignment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SizeDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.Property<string>("SubraceIndexes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TraitIndexes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Index");

                    b.HasIndex("Name");

                    b.ToTable("CatalogRaces", (string)null);
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Catalog.SkillDefinition", b =>
                {
                    b.Property<string>("Index")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AbilityIndex")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Index");

                    b.HasIndex("Name");

                    b.ToTable("CatalogSkills", (string)null);
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Catalog.SpellDefinition", b =>
                {
                    b.Property<string>("Index")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AttackType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("CastingTime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClassIndexes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Components")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Concentration")
                        .HasColumnType("boolean");

                    b.Property<string>("DamageJson")
                        .HasColumnType("text");

                    b.Property<string>("DcAbility")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HigherLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Material")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Ritual")
                        .HasColumnType("boolean");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SubclassIndexes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Index");

                    b.HasIndex("Level");

                    b.HasIndex("Name");

                    b.ToTable("CatalogSpells", (string)null);
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Catalog.SubclassDefinition", b =>
                {
                    b.Property<string>("Index")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClassIndex")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Flavor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Index");

                    b.HasIndex("ClassIndex");

                    b.HasIndex("Name");

                    b.ToTable("CatalogSubclasses", (string)null);
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Catalog.SubclassLevel", b =>
                {
                    b.Property<string>("Index")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FeatureIndexes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("SubclassIndex")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Index");

                    b.HasIndex("SubclassIndex", "Level")
                        .IsUnique();

                    b.ToTable("CatalogSubclassLevels", (string)null);
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Catalog.SubraceDefinition", b =>
                {
                    b.Property<string>("Index")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AbilityBonusesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RaceIndex")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TraitIndexes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Index");

                    b.HasIndex("Name");

                    b.HasIndex("RaceIndex");

                    b.ToTable("CatalogSubraces", (string)null);
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Catalog.TraitDefinition", b =>
                {
                    b.Property<string>("Index")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RaceIndexes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubraceIndexes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Index");

                    b.HasIndex("Name");

                    b.ToTable("CatalogTraits", (string)null);
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Users.PasswordToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordTokens", (string)null);
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Campaigns.Campaign", b =>
                {
                    b.HasOne("OpenTrpg.Core.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Campaigns.CampaignMember", b =>
                {
                    b.HasOne("OpenTrpg.Core.Domain.Campaigns.Campaign", null)
                        .WithMany("Members")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenTrpg.Core.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Campaigns.OwnershipTransfer", b =>
                {
                    b.HasOne("OpenTrpg.Core.Domain.Campaigns.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenTrpg.Core.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenTrpg.Core.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Catalog.ClassLevel", b =>
                {
                    b.HasOne("OpenTrpg.Core.Domain.Catalog.ClassDefinition", null)
                        .WithMany()
                        .HasForeignKey("ClassIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Catalog.FeatureDefinition", b =>
                {
                    b.HasOne("OpenTrpg.Core.Domain.Catalog.ClassDefinition", null)
                        .WithMany()
                        .HasForeignKey("ClassIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenTrpg.Core.Domain.Catalog.SubclassDefinition", null)
                        .WithMany()
                        .HasForeignKey("SubclassIndex")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Catalog.ItemTemplate", b =>
                {
                    b.HasOne("OpenTrpg.Core.Domain.Campaigns.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Catalog.SubclassDefinition", b =>
                {
                    b.HasOne("OpenTrpg.Core.Domain.Catalog.ClassDefinition", null)
                        .WithMany()
                        .HasForeignKey("ClassIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Catalog.SubclassLevel", b =>
                {
                    b.HasOne("OpenTrpg.Core.Domain.Catalog.SubclassDefinition", null)
                        .WithMany()
                        .HasForeignKey("SubclassIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Catalog.SubraceDefinition", b =>
                {
                    b.HasOne("OpenTrpg.Core.Domain.Catalog.RaceDefinition", null)
                        .WithMany()
                        .HasForeignKey("RaceIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Users.PasswordToken", b =>
                {
                    b.HasOne("OpenTrpg.Core.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Users.RefreshToken", b =>
                {
                    b.HasOne("OpenTrpg.Core.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenTrpg.Core.Domain.Campaigns.Campaign", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
