using System.Text.Json;
using Dnd.Domain.Common;

namespace Dnd.Domain.Characters;

/// <summary>
/// Limited-use resource (rage, ki, a magic item's charges...). Automatic resources (<see cref="IsAuto"/>)
/// derive from class and level and are regenerated by <see cref="Character.SyncAutoResources"/>;
/// manual ones are added by the owner or a DM.
/// </summary>
public sealed class CharacterResource
{
    public const int NameMaxLength = 100;
    public const int MaxUses = 999;

    private CharacterResource()
    {
    }

    public Guid Id { get; init; } = Guid.NewGuid();

    public Guid CharacterId { get; private set; }

    /// <summary>Stable key of automatic resources (e.g. "rage"); null for manual ones.</summary>
    public string? Key { get; private set; }

    public string Name { get; private set; } = string.Empty;

    public int Max { get; private set; }

    public int Used { get; private set; }

    public ResourceRecharge Recharge { get; private set; }

    public bool IsAuto { get; private set; }

    public int Remaining => Math.Max(0, Max - Used);

    /// <summary>Faces of the die rolled after a rest (<see cref="RollOnRest"/>), or null.</summary>
    public int? RollDie { get; private set; }

    public int? RollCount { get; private set; }

    public RestKind? RollRest { get; private set; }

    /// <summary>Persisted form of <see cref="Rolls"/>: <c>[14,3]</c>.</summary>
    public string RollsJson { get; private set; } = "[]";

    /// <summary>The dice must be rolled again (after the rest that recharges them, or when the resource appears).</summary>
    public bool RollsPending { get; private set; }

    public RollOnRest? RollOnRest =>
        RollDie is { } die && RollCount is { } count && RollRest is { } rest ? new RollOnRest(die, count, rest) : null;

    /// <summary>Values rolled after the last rest (empty while pending).</summary>
    public IReadOnlyList<int> Rolls => JsonSerializer.Deserialize<List<int>>(RollsJson) ?? [];

    internal static CharacterResource CreateAuto(Guid characterId, ResourceTemplate template)
    {
        var resource = new CharacterResource
        {
            CharacterId = characterId,
            Key = template.Key,
            Name = template.Name,
            Max = template.Max,
            Recharge = template.Recharge,
            IsAuto = true,
        };
        resource.SetRollOnRest(template.RollOnRest);
        return resource;
    }

    internal static CharacterResource CreateManual(Guid characterId, string name, int max, ResourceRecharge recharge) => new()
    {
        CharacterId = characterId,
        Name = name,
        Max = max,
        Recharge = recharge,
    };

    internal void UpdateFromTemplate(ResourceTemplate template)
    {
        Name = template.Name;
        Max = template.Max;
        Recharge = template.Recharge;
        Used = Math.Min(Used, Max);
        SetRollOnRest(template.RollOnRest);
    }

    /// <summary>After a rest: the dice of a resource that rolls after this kind of rest must be rolled again.</summary>
    internal void AfterRest(RestKind kind)
    {
        if (RollOnRest is { } roll && roll.RollsAfter(kind))
        {
            RollsJson = "[]";
            RollsPending = true;
        }
    }

    /// <summary>Stores the values rolled (exactly <see cref="RollCount"/>, each 1..die) and clears the pending flag.</summary>
    internal void RecordRolls(IReadOnlyList<int> values)
    {
        if (RollOnRest is not { } roll)
        {
            throw DomainException.RuleViolation($"{Name} no pide tiradas al descansar.");
        }

        if (values.Count != roll.Count)
        {
            throw DomainException.RuleViolation($"{Name} necesita exactamente {roll.Count} {(roll.Count == 1 ? "tirada" : "tiradas")} de {roll.Dice}.");
        }

        if (values.Any(v => v < 1 || v > roll.Die))
        {
            throw DomainException.RuleViolation($"Cada tirada de {roll.Dice} debe estar entre 1 y {roll.Die}.");
        }

        RollsJson = JsonSerializer.Serialize(values);
        RollsPending = false;
    }

    private void SetRollOnRest(RollOnRest? roll)
    {
        if (roll is null)
        {
            RollDie = null;
            RollCount = null;
            RollRest = null;
            RollsJson = "[]";
            RollsPending = false;
            return;
        }

        var changed = RollDie != roll.Die || RollCount != roll.Count;
        RollDie = roll.Die;
        RollCount = roll.Count;
        RollRest = roll.Rest;
        if (changed)
        {
            // New (or different) dice: they have to be rolled before they can be used.
            RollsJson = "[]";
            RollsPending = true;
        }
    }

    internal void SetUsed(int used) => Used = used;
}
