namespace Dnd.Domain.Characters;

/// <summary>
/// Limited-use resource (rage, ki, a magic item's charges...). Automatic resources (<see cref="IsAuto"/>)
/// derive from class and level and are regenerated by <see cref="Character.SyncAutoResources"/>;
/// manual ones are added by the owner or a DM.
/// </summary>
public sealed class CharacterResource
{
    public const int NameMaxLength = 100;
    public const int MaxUses = 999;

    private CharacterResource()
    {
    }

    public Guid Id { get; init; } = Guid.NewGuid();

    public Guid CharacterId { get; private set; }

    /// <summary>Stable key of automatic resources (e.g. "rage"); null for manual ones.</summary>
    public string? Key { get; private set; }

    public string Name { get; private set; } = string.Empty;

    public int Max { get; private set; }

    public int Used { get; private set; }

    public ResourceRecharge Recharge { get; private set; }

    public bool IsAuto { get; private set; }

    public int Remaining => Math.Max(0, Max - Used);

    internal static CharacterResource CreateAuto(Guid characterId, ResourceTemplate template) => new()
    {
        CharacterId = characterId,
        Key = template.Key,
        Name = template.Name,
        Max = template.Max,
        Recharge = template.Recharge,
        IsAuto = true,
    };

    internal static CharacterResource CreateManual(Guid characterId, string name, int max, ResourceRecharge recharge) => new()
    {
        CharacterId = characterId,
        Name = name,
        Max = max,
        Recharge = recharge,
    };

    internal void UpdateFromTemplate(ResourceTemplate template)
    {
        Name = template.Name;
        Max = template.Max;
        Recharge = template.Recharge;
        Used = Math.Min(Used, Max);
    }

    internal void SetUsed(int used) => Used = used;
}
